#!/bin/bash
# Helper function to mimic debian's `dpkg-query --show <package>` command

doshow=0
showformat='${Package} ${Version}\\n'


while [[ $# > 0 ]]
do
key="$1"

case $key in
    -W|--show)
	doshow=1
        ;;
    -f=*)
	showformat=$(echo $key | cut -d= -f2 | sed "s/\(\\\\\)/\1\1/")
	;;
    --showformat)
	showformat=$(echo $2 | sed "s/\(\\\\\)/\1\1/g")
	shift
	;;
    -*)
	doshow=0
	;;
    *)
	if [ ${doshow} -eq 1 ]; then
	    Package=$1
	    if [ "$Package" = "bubba" ]; then
		Package=bubbagen
	    fi
	    if [ "$Package" = "bubba3-kernel" ]; then
		Version=$(uname -r)
	    else 
		Version=$(find /var/db/pkg/ -mindepth 2 -maxdepth 2 -type d \( -name ${Package}-[0-9]* -o -name ${Package}-bin-[0-9]* \) | awk -F/ '{print $NF}' | eval "sed \"s/^${Package}-\(bin-\)\?//\"")
	    fi
	    if [ "$Version" = "" ]; then
		Status="unknown ok not-installed"
	    else
		Status="install ok installed"
	    fi

	    Package=$1
	    eval "echo -e -n ${showformat}"
	fi
            # unknown option
        ;;
esac
shift
done
