#!/sbin/openrc-run

DESC="File Transfer Daemon"
NAME=ftd
DAEMON=/opt/bubba/sbin/$NAME
PIDFILE=/var/run/$NAME.pid

depend() {
        need net
}

start() {
        ebegin "Starting $DESC"
		start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE --background --exec $DAEMON
        eend $?
}

stop() {
        ebegin "Stopping $DESC"
        start-stop-daemon --stop --quiet --pidfile $PIDFILE
        eend $?
}

